### PR TITLE
Cart basic #38

### LINKED ISSUE #38: Cart: add item (possible from product list or product detail pages)

### PR DESCRIPTION
**Pull request by onggunhao**
Closes #38 (partially)

### CODE REVIEW

**Comment by onggunhao** [comment]
- Visually show the cart list
- Check if item has been added to cart, if so increase quantity

**Comment by onggunhao** [comment]
- Add snackbar to bottom of screen when it is added

**Comment by knoebelja** [comment]
Looks good! Looks functional

**Review by knoebelja — APPROVED** [review]
Looks good! Functions as should

**Pull request merged**
